on:
  workflow_dispatch:
    inputs:
      release_notes:
        description: 'Release notes'
        required: true
        default: 'Changes in this Release\n- First Change\n- Second Change'
      release_name:
        description: 'Release name'
        required: true

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Get version from package.json
        id: get_version
        run: |
          version=$(jq -r '.version' package.json)
          echo "::set-output name=version::$version"
      
      - name: Construct release name
        id: construct_release_name
        run: |
          release_name="${{ steps.get_version.outputs.version }}: ${{ github.event.inputs.release_name }}"
          echo "::set-output name=release_name::$release_name"
      
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ github.event.inputs.release_notes }}
          name: ${{ steps.construct_release_name.outputs.release_name }}
          tag_name: ${{ steps.get_version.outputs.version }}
          repository: antonidag/dummy-data-cli
          token: ${{ secrets.GH_PAT }}
          make_latest: true
          draft: false
          prerelease: false
